column_mappings:
    default:
        ppid: pid
        phid: hid
        pdlcar: has_licence
        pwkstat: employment
        pnotrips: no_trips
        pawfh: can_wfh
        poccupa: occupation
    LTDS2223:
        ppid: pid
        phid: hid
        pdlcar: has_licence
        pnotrips: no_trips
        pawfh: can_wfh
        poccupa: occupation
    LTDS1920:
        ppid: pid
        phid: hid
        pdlcar: has_licence
        pnotrips: no_trips
        pawfh: can_wfh
        poccupa: occupation

has_licence:
    default:
        -2: "unknown"
        -1: "no"
        1: "yes"
        2: "no"

employment:
    default:
        1 FT Worker: employed
        2 PT Worker: employed
        3 Student: student
        4 Under 16: student
        5 Not Working: unemployed
        6 Retired: retired
        
    LTDS2425:
        Not Working: unemployed
        FT Worker: employed
        Under 16: student
        Retired: retired
        Student: student
        PT Worker: employed
        Other: other

can_wfh:
    default:
        1: "yes"
        2: "yes"
        3: "no"
        4: "no"
        -1: "n/a"

occupation:
    default:
        1: professional
        2: clerical
        3: managerial
        4: technical
        5: manual
        6: manual
        7: managerial
        8: professional
        -1: n/a