column_mappings:
    default:
        # shid: hid
        spid: pid
        stid: tid
        slenn: distance # prob km?
    LTDS1920:
        # shid: hid
        spid: pid
        stid: tid
        slen100m: distance # prob km?
