# Person-level dictionary for <source>
# Map raw CSV column names to template field names under column_mappings.
# Add value mappings for categorical fields below.

column_mappings:
  idx: pid
  Q1_1: age
  SQ2: sex
  R1: has_licence
  R2: student
  R3: employed
  R3_2: occupation
  # RAW_COL_NAME: education
  # RAW_COL_NAME: disability
  R3_4_a: can_wfh
  # RAW_COL_NAME: relationship
  # RAW_COL_NAME: race
  DATE: date

  ### HH attributes ###
  Q1: hh_size
  Q3: hh_income  # monthly
  Q2: dwelling
  # RAW_COL_NAME: ownership
  Q4_1: cars
  Q4_2: vans
  Q4_6: motorcycles
  SQ1_8: rurality
  # RAW_COL_NAME: weight

weekday:
  1: monday
  2: tuesday
  3: wednesday
  4: thursday
  5: friday
  6: saturday
  7: sunday

# sex mapping
  # Valid values: male, female, other, unknown
sex:
  1: male
  2: female

# has_licence mapping
  # Valid values: n/a, yes, no, unknown
has_licence:
  1: "yes"
  2: "no"
  99: "unknown"

# student mapping
student:
  0: "n/a"
  1: "yes"
  2: "yes"
  3: "yes"
  4: "yes"
  98: "n/a"
  99: "unknown"

employed:
  1: "yes"
  2: "yes"
  3: "no"

# occupation mapping
  # Valid values: n/a, clerical, manual, managerial, operator, professional, service, other, technical, unknown
occupation:
  1: other # self employed
  2: service
  3: operator
  4: manual
  5: technical
  6: clerical
  7: managerial
  8: professional
  9: other  # freelance
  10: manual
  11: manual
  96: other

# can_wfh mapping
  # Valid values: yes, no, unknown, n/a
can_wfh:
  1: "yes"
  2: "yes"
  3: "yes"
  4: "yes"
  97: "n/a"
  98: "no"
  99: "unknown"

hh_income:
  1: [0,1]  # million KRW
  2: [1,3]
  3: [3,5]
  4: [5,10]
  5: [10,15]
  6: [15,25]
  99: [0]

# dwelling mapping
  # Valid values: house, flat, other, unknown
dwelling:
  1: flat
  2: house
  3: house
  4: house
  5: other
  97: other

# ownership mapping
  # Valid values: owned, rented, other, unknown
ownership:
  # 1: owned
  # 1: rented
  # 1: other
  # 1: unknown

# rurality mapping
  # Valid values: urban, suburban, rural, unknown
rurality:
  # 1: urban
  # 1: suburban
  # 1: rural
  # 1: unknown
