column_mappings:
    default:
        persid: pid
        hhid: hid
        agegroup: age
        sex: sex
        relationship: relationship
        nolicence: has_licence
        fulltimework: ft
        parttimework: pt
        # anywork: anywork
        studying: studying
        activities: activity  # Retired Unemployed
        anzsco1: occupation
        # anzsco2: occupation_detailed
    2012-2020:
        persid: pid
        hhid: hid
        age: age
        sex: sex
        relationship: relationship
        nolicence: has_licence
        # anywork: anywork
        fulltimework: ft
        parttimework: pt
        studying: studying
        activities: activity
        anzsco1: occupation
        # anzsco2: occupation_detailed


sex:
    default: {
        M: male,
        F: female,
        Male: male,
        Female: female
    }
relationship:
    default: {
        Self: self,
        Spouse: partner,
        Child: child,
        Grandchild: child,
        Other relative: other,
        Sibling: sibling,
        Other: other,
        Non related: unrelated,
        Unrelated: unrelated,
    }
has_licence:
    default: {
        Some Licence: "yes",
        No Licence: "no",   
    }
occupation:
    default: {
        Clerical and Administrative Workers: clerical,
        Community and Personal Service Workers: service,
        Labourers: manual,
        Machinery Operators and Drivers: operator,
        Managers: managerial,
        Missing/Refused: unknown,
        Not in Work Force: n/a,
        Professionals: professional,
        Sales Workers: service,
        Technicians and Trades Workers: technical,
    }
 
   