from pathlib import Path

import polars as pl

from foundata import fix
from foundata.utils import (
    compute_avg_speed,
    expand_root,
    sample_to_euro,
    table_joiner,
)

SOURCE = "odin"
DATA_FILE = "ODiN2018_Databestand_v2.0.tab"
HM_TO_KM = 0.1  # hectometres → kilometres


def load(
    data_root: str | Path,
    hh_config: dict,
    person_config: dict,
    trips_config: dict,
) -> tuple[pl.DataFrame, pl.DataFrame]:
    print("Loading ODIN...")
    hhs = load_households(data_root, hh_config)
    persons = load_persons(data_root, person_config)
    attributes = table_joiner(hhs, persons, on="hid")
    trips = load_trips(data_root, trips_config)

    attributes = compute_avg_speed(attributes, trips)

    attributes = attributes.with_columns(
        pid=pl.lit(SOURCE) + pl.col("pid").cast(pl.String),
        hid=pl.lit(SOURCE) + pl.col("hid").cast(pl.String),
        source=pl.lit(SOURCE),
        country=pl.lit("nl"),
    )
    trips = trips.with_columns(
        pid=pl.lit(SOURCE) + pl.col("pid").cast(pl.String)
    )

    return attributes, trips


def load_households(root: str | Path, config: dict) -> pl.DataFrame:
    root = expand_root(root)
    column_mapping = config["column_mappings"]

    data = pl.read_csv(root / DATA_FILE, separator="\t", infer_schema_length=0)
    # OP == "1" marks the first (and only unique) row per respondent
    data = data.filter(pl.col("OP") == "1")
    data = data.select(column_mapping.keys()).rename(column_mapping)

    data = data.with_columns(
        hh_income=pl.col("hh_income")
        .replace_strict(config["hh_income"])
        .map_elements(sample_to_euro, return_dtype=pl.Int32),
        hh_size=pl.col("hh_size").cast(pl.Int32, strict=False),
        vehicles=pl.col("vehicles").cast(pl.Int32, strict=False),
        hh_zone=pl.col("hh_zone").replace_strict(config["hh_zone"]),
        day=pl.col("day").replace_strict(config["day"]),
        year=pl.col("year").cast(pl.Int32, strict=False),
        month=pl.col("month").cast(pl.Int8, strict=False),
        dwelling=pl.lit("unknown"),
        ownership=pl.lit("unknown"),
    )

    return data.filter(pl.col("hid").is_not_null())


def load_persons(root: str | Path, config: dict) -> pl.DataFrame:
    root = expand_root(root)
    column_mapping = config["column_mappings"]

    data = pl.read_csv(root / DATA_FILE, separator="\t", infer_schema_length=0)
    data = data.filter(pl.col("OP") == "1")
    data = data.select(column_mapping.keys()).rename(column_mapping)

    # OPID serves as both pid and hid
    data = data.with_columns(hid=pl.col("pid"))

    data = data.with_columns(
        age=pl.col("age").cast(pl.Int32, strict=False),
        sex=pl.col("sex").replace_strict(config["sex"]),
        employment=pl.col("employment").replace_strict(config["employment"]),
        education=pl.col("education").replace_strict(config["education"]),
        has_licence=pl.col("has_licence").replace_strict(config["has_licence"]),
        relationship=pl.col("relationship").replace_strict(
            config["relationship"]
        ),
        race=pl.col("race").replace_strict(config["race"]),
        weight=pl.col("weight").cast(pl.Float32, strict=False),
        disability=pl.lit("unknown"),
        can_wfh=pl.lit("unknown"),
        occupation=pl.lit("unknown"),
    )

    return data.filter(pl.col("pid").is_not_null())


def load_trips(root: str | Path, config: dict) -> pl.DataFrame:
    root = expand_root(root)
    column_mapping = config["column_mappings"]

    data = pl.read_csv(root / DATA_FILE, separator="\t", infer_schema_length=0)
    # Verpl == "1" selects regular (non-series, non-professional-truck) trips
    data = data.filter(pl.col("Verpl") == "1")

    # Derive zone from Sted before column selection (maps to two output columns)
    data = data.with_columns(
        ozone=pl.col("Sted").replace_strict(config["ozone"]),
        dzone=pl.col("Sted").replace_strict(config["dzone"]),
    )

    data = data.select(list(column_mapping.keys()) + ["ozone", "dzone"]).rename(
        column_mapping
    )

    data = data.with_columns(
        tst=(
            pl.col("tst_hour").cast(pl.Int32, strict=False) * 60
            + pl.col("tst_min").cast(pl.Int32, strict=False)
        ),
        tet=(
            pl.col("tet_hour").cast(pl.Int32, strict=False) * 60
            + pl.col("tet_min").cast(pl.Int32, strict=False)
        ),
        distance=pl.col("distance").cast(pl.Float32, strict=False) * HM_TO_KM,
        seq=pl.col("seq").cast(pl.Int8, strict=False),
        mode=pl.col("mode").replace_strict(config["mode"]),
        oact=pl.col("oact").replace_strict(config["oact"]),
        dact=pl.col("dact").replace_strict(config["dact"]),
    ).drop(["tst_hour", "tst_min", "tet_hour", "tet_min"])

    data = data.with_columns(hid=pl.col("pid"))
    return fix.day_wrap(data)


COLUMN_TRANSLATIONS = {
    # Person-level (P)
    "OP": "new_person",
    "OPID": "person_id",
    "Steekproef": "sample_indicator",
    "Mode": "response_mode",
    "HHPers": "hh_persons",
    "HHSam": "hh_composition",
    "HHPlOP": "hh_position",
    "HHLft1": "hh_members_under_6",
    "HHLft2": "hh_members_6_to_11",
    "HHLft3": "hh_members_12_to_17",
    "HHLft4": "hh_members_18_plus",
    "WoPC": "home_postal_code",
    "WoGem": "home_municipality",
    "Wogem": "home_municipality",
    "Sted": "urbanisation_class",
    "GemGr": "municipality_population_class",
    "Prov": "province",
    "Corop": "corop_region",
    "BuurtAdam": "amsterdam_neighbourhood",
    "MRA": "amsterdam_metro_area",
    "Geslacht": "gender",
    "Leeftijd": "age",
    "KLeeft": "age_class",
    "Herkomst": "migration_background",
    "BetWerk": "paid_work",
    "OnbBez": "unpaid_activity",
    "MaatsPart": "social_participation",
    "Opleiding": "education_level",
    "HHBestInkG": "hh_disposable_income_decile",
    "HHGestInkG": "hh_standardised_income_decile",
    "HHLaagInk": "hh_low_income_threshold_deviation",
    "HHSocInk": "hh_social_minimum_deviation",
    "HHWelvG": "hh_wealth_decile",
    "HHRijbewijsAu": "hh_car_licences",
    "HHRijbewijsMo": "hh_motorcycle_licences",
    "HHRijbewijsBr": "hh_moped_licences",
    "OPRijbewijsAu": "has_car_licence",
    "OPRijbewijsMo": "has_motorcycle_licence",
    "OPRijbewijsBr": "has_moped_licence",
    "HHAuto": "hh_cars",
    "HHAutoL": "hh_leased_company_cars",
    "OPAuto": "person_cars",
    "BrandstofPa1": "car1_fuel_primary",
    "XBrandstofPa1": "car1_fuel_secondary",
    "BrandstofEPa1": "car1_electric_type",
    "BouwjaarPa1": "car1_build_year",
    "KBouwjaarPa1": "car1_build_year_class",
    "KGewichtPa1": "car1_weight_class",
    "TenaamPa1": "car1_registration_holder",
    "BrandstofPa2": "car2_fuel_primary",
    "XBrandstofPa2": "car2_fuel_secondary",
    "BrandstofEPa2": "car2_electric_type",
    "BouwjaarPa2": "car2_build_year",
    "KBouwjaarPa2": "car2_build_year_class",
    "KGewichtPa2": "car2_weight_class",
    "TenaamPa2": "car2_registration_holder",
    "BrandstofPaL": "lease_car_fuel_primary",
    "XBrandstofPaL": "lease_car_fuel_secondary",
    "BrandstofEPaL": "lease_car_electric_type",
    "BouwjaarPaL": "lease_car_build_year",
    "KBouwjaarPaL": "lease_car_build_year_class",
    "KGewichtPaL": "lease_car_weight_class",
    "HHMotor": "hh_motorcycles",
    "OPMotor": "person_motorcycles",
    "HHBrom": "hh_mopeds",
    "OPBrom": "person_mopeds",
    "HHSnor": "hh_scooters",
    "OPSnor": "person_scooters",
    "HHEFiets": "hh_has_ebike",
    "HHBezitVm": "hh_vehicle_ownership",
    "OPBezitVm": "person_vehicle_ownership",
    "FqNEFiets": "freq_bicycle",
    "FqEFiets": "freq_ebike",
    "FqBTM": "freq_bus_tram_metro",
    "FqTrein": "freq_train",
    "FqAutoB": "freq_car_driver",
    "FqAutoP": "freq_car_passenger",
    "FqBrSnor": "freq_moped_scooter",
    "OVStKaart": "student_transit_card",
    "Jaar": "year",
    "Maand": "month",
    "Week": "week",
    "Dag": "day",
    "Weekdag": "weekday",
    "Feestdag": "public_holiday",
    "Weggeweest": "traveled",
    "RedenNW": "reason_not_traveled",
    "RedenNWZ": "reason_not_traveled_illness_duration",
    "RedenNWW": "reason_not_traveled_weather_type",
    "RedenNWB": "reason_not_traveled_abroad",
    "AantVpl": "n_trips",
    "AantOVVpl": "n_transit_trips",
    "AantSVpl": "n_series_trips",
    "EFiets": "ebike_type_used",
    "AutoEig": "used_own_car",
    "AutoHhL": "used_household_car",
    "AutoHhl": "used_household_car",
    "AutoLWg": "used_employer_lease_car",
    "AutoLPl": "used_private_lease_car",
    "AutoBed": "used_company_car",
    "AutoDOrg": "used_carshare_organisation",
    "AutoDPart": "used_carshare_platform",
    "AutoDBek": "used_carshare_friends",
    "AutoLeen": "used_borrowed_car",
    "AutoHuur": "used_rental_car",
    "AutoAnd": "used_other_car",
    "ByzDag": "atypical_day",
    "ByzAdr": "atypical_addresses",
    "ByzVvm": "atypical_modes",
    "ByzTyd": "atypical_times",
    "ByzDuur": "atypical_duration",
    "ByzRoute": "atypical_route",
    "ByzReden": "atypical_reason",
    "ReisduurOP": "total_travel_time_min",
    "AfstandOP": "total_distance_hm",
    "AfstandSOP": "total_series_distance_hm",
    # Trip-level (V)
    "Verpl": "new_trip",
    "VerplID": "trip_id",
    "VerplNr": "trip_number",
    "Toer": "round_trip",
    "AantRit": "n_legs",
    "Doel": "purpose",
    "MotiefV": "motive",
    "KMotiefV": "motive_class",
    "MeerWink": "multiple_shops",
    "AardWerk": "work_activity_type",
    "VertLoc": "origin_location_type",
    "VertGeb": "origin_region",
    "VertPC": "origin_postal_code",
    "VertPCBL": "origin_postal_code_abroad",
    "VertGem": "origin_municipality",
    "VertProv": "origin_province",
    "VertCorop": "origin_corop",
    "VertMRA": "origin_amsterdam_metro_area",
    "AankGeb": "destination_region",
    "AankPC": "destination_postal_code",
    "AankPCBL": "destination_postal_code_abroad",
    "AankGem": "destination_municipality",
    "AankProv": "destination_province",
    "AankCorop": "destination_corop",
    "AankMRA": "destination_amsterdam_metro_area",
    "PCG": "border_crossing_postal_code",
    "GemG": "border_crossing_municipality",
    "PCBLG": "border_crossing_foreign_postal_code",
    "AfstV": "trip_distance_hm",
    "KAfstV": "trip_distance_class",
    "Hvm": "main_mode",
    "HvmRol": "main_mode_role",
    "KHvm": "main_mode_class",
    "VertUur": "departure_hour",
    "VertMin": "departure_minute",
    "KVertTijd": "departure_time_class",
    "AankUur": "arrival_hour",
    "AankMin": "arrival_minute",
    "Reisduur": "travel_time_min",
    "KReisduur": "travel_time_class",
    "ActDuur": "activity_duration_min",
    "Kind6": "children_under_6_along",
    "VolgWerk": "work_trip_sequence",
    "SAantAdr": "series_n_addresses",
    "SDezPlts": "series_same_place",
    "SPlaats1": "series_place_1",
    "SPlaats2": "series_place_2",
    "SPlaats3": "series_place_3",
    "SPlaats4": "series_place_4",
    "SPlaats5": "series_place_5",
    "AfstS": "series_distance_hm",
    "AfstSBL": "series_distance_abroad_hm",
    "SVvm1": "series_mode_1",
    "SVvm2": "series_mode_2",
    "SVvm3": "series_mode_3",
    "SVvm4": "series_mode_4",
    "SBegUur": "series_start_hour",
    "SBegMin": "series_start_minute",
    "SEindUur": "series_end_hour",
    "SEindMin": "series_end_minute",
    "CorrVerpl": "trip_to_leg_correction",
    "GehBLVer": "foreign_trip_removed",
    # Leg-level (R)
    "Rit": "new_leg",
    "RitID": "leg_id",
    "RitNr": "leg_number",
    "AfstR": "leg_distance_hm",
    "AfstRBL": "leg_distance_abroad_hm",
    "KAfstR": "leg_distance_class",
    "Rvm": "leg_mode",
    "RvmRol": "leg_mode_role",
    "RAantIn": "car_occupants",
    "KRvm": "leg_mode_class",
    "RVertUur": "leg_departure_hour",
    "RVertMin": "leg_departure_minute",
    "RAankUur": "leg_arrival_hour",
    "RAankMin": "leg_arrival_minute",
    "RReisduur": "leg_travel_time_min",
    "RReisduurBL": "leg_travel_time_abroad_min",
    "RVertStat": "train_departure_station",
    "RAankStat": "train_arrival_station",
    "RTSamen": "train_group_size",
    "RCorrSnelh": "speed_correction",
    "RVliegVer": "flight_leg_removed",
    # Weight factors (W)
    "FactorH": "weight_household",
    "FactorP": "weight_person",
    "FactorV": "weight_trip",
}

LEVEL_TRANSLATIONS = {"P": "person", "V": "trip", "R": "leg", "W": "weight"}

VARIABLE_LABELS = {
    "OP": "New person indicator",
    "OPID": "Unique person ID",
    "Steekproef": "Sample indicator",
    "Mode": "Response mode",
    "HHPers": "Number of persons in household",
    "HHSam": "Household composition",
    "HHPlOP": "Position of respondent in household relative to household core",
    "HHLft1": "Number of household members under 6 years",
    "HHLft2": "Number of household members aged 6–11",
    "HHLft3": "Number of household members aged 12–17",
    "HHLft4": "Number of household members aged 18 or older",
    "WoPC": "Home postal code",
    "WoGem": "Home municipality",
    "Wogem": "Home municipality",
    "Sted": "Urbanisation class of home municipality",
    "GemGr": "Population size class of home municipality",
    "Prov": "Province of home municipality",
    "Corop": "COROP region of home municipality",
    "BuurtAdam": "Neighbourhood combination Amsterdam",
    "MRA": "Amsterdam Metropolitan Area",
    "Geslacht": "Gender of respondent",
    "Leeftijd": "Age of respondent",
    "KLeeft": "Age class of respondent",
    "Herkomst": "Migration background of respondent",
    "BetWerk": "Paid work of respondent",
    "OnbBez": "Unpaid activity of respondent",
    "MaatsPart": "Social participation of respondent",
    "Opleiding": "Highest completed education of respondent",
    "HHBestInkG": "Disposable household income (10% groups)",
    "HHGestInkG": "Standardised disposable household income (10% groups)",
    "HHLaagInk": "Deviation from low income threshold",
    "HHSocInk": "Deviation from social minimum income",
    "HHWelvG": "Household wealth (10% groups)",
    "HHRijbewijsAu": "Number of car driving licences in household",
    "HHRijbewijsMo": "Number of motorcycle licences in household",
    "HHRijbewijsBr": "Number of moped licences in household",
    "OPRijbewijsAu": "Respondent holds car driving licence",
    "OPRijbewijsMo": "Respondent holds motorcycle licence",
    "OPRijbewijsBr": "Respondent holds moped licence",
    "HHAuto": "Number of cars in household",
    "HHAutoL": "Number of leased/company cars in household",
    "OPAuto": "Number of cars registered to respondent",
    "BrandstofPa1": "Primary fuel type of youngest household car",
    "XBrandstofPa1": "Secondary fuel type of youngest household car",
    "BrandstofEPa1": "Electric car type of youngest household car",
    "BouwjaarPa1": "Build year of youngest household car",
    "KBouwjaarPa1": "Build year class of youngest household car",
    "KGewichtPa1": "Weight class of youngest household car",
    "TenaamPa1": "Registration holder of youngest household car",
    "BrandstofPa2": "Primary fuel type of second youngest household car",
    "XBrandstofPa2": "Secondary fuel type of second youngest household car",
    "BrandstofEPa2": "Electric car type of second youngest household car",
    "BouwjaarPa2": "Build year of second youngest household car",
    "KBouwjaarPa2": "Build year class of second youngest household car",
    "KGewichtPa2": "Weight class of second youngest household car",
    "TenaamPa2": "Registration holder of second youngest household car",
    "BrandstofPaL": "Primary fuel type of lease/company car in household",
    "XBrandstofPaL": "Secondary fuel type of lease/company car in household",
    "BrandstofEPaL": "Electric car type of lease/company car in household",
    "BouwjaarPaL": "Build year of lease/company car in household",
    "KBouwjaarPaL": "Build year class of lease/company car in household",
    "KGewichtPaL": "Weight class of lease/company car in household",
    "HHMotor": "Number of motorcycles in household",
    "OPMotor": "Number of motorcycles registered to respondent",
    "HHBrom": "Number of mopeds in household",
    "OPBrom": "Number of mopeds registered to respondent",
    "HHSnor": "Number of scooters in household",
    "OPSnor": "Number of scooters registered to respondent",
    "HHEFiets": "Electric bicycle in household",
    "HHBezitVm": "Vehicle ownership of household",
    "OPBezitVm": "Vehicle ownership of respondent",
    "FqNEFiets": "Frequency of use: non-electric bicycle",
    "FqEFiets": "Frequency of use: electric bicycle",
    "FqBTM": "Frequency of use: bus, tram and/or metro",
    "FqTrein": "Frequency of use: train",
    "FqAutoB": "Frequency of use: car as driver",
    "FqAutoP": "Frequency of use: car as passenger",
    "FqBrSnor": "Frequency of use: moped and/or scooter",
    "OVStKaart": "Respondent holds student public transport card",
    "Jaar": "Reporting year",
    "Maand": "Reporting month",
    "Week": "Reporting week",
    "Dag": "Reporting day",
    "Weekdag": "Reporting weekday",
    "Feestdag": "Reporting day is public holiday",
    "Weggeweest": "Respondent traveled in the Netherlands",
    "RedenNW": "Reason for not traveling",
    "RedenNWZ": "Not traveled: duration of illness",
    "RedenNWW": "Not traveled: type of weather",
    "RedenNWB": "Not traveled: reason for stay abroad",
    "AantVpl": "Number of regular trips by respondent in the Netherlands",
    "AantOVVpl": "Number of regular public transport trips by respondent in the Netherlands",
    "AantSVpl": "Number of series trips (excl. professional truck) by respondent in the Netherlands",
    "EFiets": "Type of electric bicycle used",
    "AutoEig": "Used own car",
    "AutoHhL": "Used household member's car",
    "AutoHhl": "Used household member's car",
    "AutoLWg": "Used employer lease car",
    "AutoLPl": "Used private lease car",
    "AutoBed": "Used company car",
    "AutoDOrg": "Used shared car from organisation",
    "AutoDPart": "Used shared car from private person via online platform",
    "AutoDBek": "Used shared car with friends/acquaintances",
    "AutoLeen": "Used borrowed car",
    "AutoHuur": "Used rental car",
    "AutoAnd": "Used other type of car",
    "ByzDag": "Special circumstances on reporting day",
    "ByzAdr": "Special circumstance: different addresses",
    "ByzVvm": "Special circumstance: different modes of transport",
    "ByzTyd": "Special circumstance: different times",
    "ByzDuur": "Special circumstance: different travel duration",
    "ByzRoute": "Special circumstance: different route",
    "ByzReden": "Reason for different travel pattern",
    "ReisduurOP": "Total travel time for regular trips by respondent in the Netherlands (minutes)",
    "AfstandOP": "Total distance for regular trips by respondent in the Netherlands (hectometres)",
    "AfstandSOP": "Total distance for series trips by respondent in the Netherlands (hectometres)",
    "Verpl": "New trip indicator",
    "VerplID": "Unique trip ID",
    "VerplNr": "Trip number",
    "Toer": "Departure point equals arrival point (round trip)",
    "AantRit": "Number of legs in trip",
    "Doel": "Destination / purpose",
    "MotiefV": "Trip motive",
    "KMotiefV": "Trip motive class",
    "MeerWink": "Multiple shops visited",
    "AardWerk": "Nature of professional work activity",
    "VertLoc": "Departure location type",
    "VertGeb": "Departure region",
    "VertPC": "Departure postal code",
    "VertPCBL": "Departure postal code abroad",
    "VertGem": "Departure municipality",
    "VertProv": "Departure province",
    "VertCorop": "Departure COROP region",
    "VertMRA": "Departure Amsterdam Metropolitan Area zone",
    "AankGeb": "Arrival region",
    "AankPC": "Arrival postal code",
    "AankPCBL": "Arrival postal code abroad",
    "AankGem": "Arrival municipality",
    "AankProv": "Arrival province",
    "AankCorop": "Arrival COROP region",
    "AankMRA": "Arrival Amsterdam Metropolitan Area zone",
    "PCG": "Dutch postal code of border crossing",
    "GemG": "Dutch municipality of border crossing",
    "PCBLG": "Foreign postal code of border crossing",
    "AfstV": "Trip distance in the Netherlands (hectometres)",
    "KAfstV": "Trip distance class in the Netherlands",
    "Hvm": "Main mode of transport",
    "HvmRol": "Role in main mode of transport",
    "KHvm": "Main mode of transport class",
    "VertUur": "Departure hour",
    "VertMin": "Departure minute",
    "KVertTijd": "Departure time class",
    "AankUur": "Arrival hour",
    "AankMin": "Arrival minute",
    "Reisduur": "Travel duration in the Netherlands (minutes)",
    "KReisduur": "Travel duration class in the Netherlands",
    "ActDuur": "Activity duration (minutes)",
    "Kind6": "Children under 6 travelling along",
    "VolgWerk": "Work trip sequence",
    "SAantAdr": "Number of addresses visited in series trip",
    "SDezPlts": "All addresses in the same place",
    "SPlaats1": "Series trip place name 1",
    "SPlaats2": "Series trip place name 2",
    "SPlaats3": "Series trip place name 3",
    "SPlaats4": "Series trip place name 4",
    "SPlaats5": "Series trip place name 5",
    "AfstS": "Series trip distance in the Netherlands (hectometres)",
    "AfstSBL": "Series trip distance abroad (hectometres)",
    "SVvm1": "Series trip: mode of transport 1",
    "SVvm2": "Series trip: mode of transport 2",
    "SVvm3": "Series trip: mode of transport 3",
    "SVvm4": "Series trip: mode of transport 4",
    "SBegUur": "Series trip start hour",
    "SBegMin": "Series trip start minute",
    "SEindUur": "Series trip end hour",
    "SEindMin": "Series trip end minute",
    "CorrVerpl": "Trip-to-leg correction applied",
    "GehBLVer": "Entirely foreign trip removed",
    "Rit": "New leg indicator",
    "RitID": "Unique leg ID",
    "RitNr": "Leg number",
    "AfstR": "Leg distance in the Netherlands (hectometres)",
    "AfstRBL": "Leg distance abroad (hectometres)",
    "KAfstR": "Leg distance class in the Netherlands",
    "Rvm": "Leg mode of transport",
    "RvmRol": "Role in leg mode of transport",
    "RAantIn": "Number of car occupants",
    "KRvm": "Leg mode of transport class",
    "RVertUur": "Leg departure hour",
    "RVertMin": "Leg departure minute",
    "RAankUur": "Leg arrival hour",
    "RAankMin": "Leg arrival minute",
    "RReisduur": "Leg travel duration in the Netherlands (minutes)",
    "RReisduurBL": "Leg travel duration abroad (minutes)",
    "RVertStat": "Train leg departure station",
    "RAankStat": "Train leg arrival station",
    "RTSamen": "Train travel group size",
    "RCorrSnelh": "Speed correction",
    "RVliegVer": "Flight leg removed",
    "FactorH": "Household weight factor",
    "FactorP": "Person weight factor",
    "FactorV": "Trip weight factor",
}

CODE_LABEL_TRANSLATIONS = {
    # Generic
    "Ja": "Yes",
    "Nee": "No",
    "Onbekend": "Unknown",
    "Anders": "Other",
    "Beide": "Both",
    "Overig": "Other",
    "Nederland": "Netherlands",
    # Missing / not applicable
    "missing indien geen verplaatsing": "missing if no trip",
    "missing indien geen verplaatsing of indien een serieverplaatsing": "missing if no trip or if series trip",
    "missing indien geen verplaatsing of indien geen serieverplaatsing": "missing if no trip or if not a series trip",
    "missing indien geen verplaatsing of laatste verplaatsing of serieverplaatsing": "missing if no trip, last trip, or series trip",
    "leeg indien geen verplaatsing": "empty if no trip",
    "leeg indien geen verplaatsing of geen serieverplaatsing": "empty if no trip or no series trip",
    "plaatsnaam of <geen plaatsnaam gerespondeerd>": "place name or <no place name given>",
    "{zie tabblad BuurtAdam}": "{see sheet BuurtAdam}",
    "{zie tabblad Corop}": "{see sheet Corop}",
    "{zie tabblad RVertStat & RAankStat}": "{see sheet RVertStat & RAankStat}",
    "{zie tabblad VertGeb & AankGeb}": "{see sheet VertGeb & AankGeb}",
    "{zie tabblad Wogem}": "{see sheet Wogem}",
    # Person / sample
    "Geen nieuwe persoon": "Not a new person",
    "Nieuwe persoon": "New person",
    "Basisonderzoek": "Core survey",
    "Meerwerk Noordvleugel": "Additional survey North Wing",
    "Cawi": "CAWI",
    # Household size
    "10 personen of meer": "10 or more persons",
    # Household composition
    "Eenpersoonshuishouden": "Single-person household",
    "Paar": "Couple",
    "Paar + kind(eren)": "Couple with child(ren)",
    "Paar + kind(eren) + ander(en)": "Couple with child(ren) and other(s)",
    "Paar + ander(en)": "Couple with other(s)",
    "Eenouderhuishouden + kind(eren)": "Single-parent household with child(ren)",
    "Eenouderhuishouden + kind(eren) + ander(en)": "Single-parent household with child(ren) and other(s)",
    "Overig huishouden": "Other household type",
    # Household position
    "Alleenstaande (eenpersoonshuishouden)": "Single (one-person household)",
    "Eenpersoonshuishoudkern (meerpersoonshuishouden)": "Single-person household core (multi-person household)",
    "Echtgeno(o)t(e)/partner (lid huishoudkern)": "Spouse/partner (household core member)",
    "Kind": "Child",
    "Overig lid van het huishouden": "Other household member",
    # Urbanisation
    "Zeer sterk stedelijk": "Very highly urban",
    "Sterk stedelijk": "Highly urban",
    "Matig stedelijk": "Moderately urban",
    "Weinig stedelijk": "Slightly urban",
    "Niet stedelijk": "Not urban",
    # Population size
    "Tot 5.000 inwoners": "Under 5,000 inhabitants",
    "5.000 tot 10.000 inwoners": "5,000–10,000 inhabitants",
    "10.000 tot 20.000 inwoners": "10,000–20,000 inhabitants",
    "20.000 tot 50.000 inwoners": "20,000–50,000 inhabitants",
    "50.000 tot 100.000 inwoners": "50,000–100,000 inhabitants",
    "100.000 tot 150.000 inwoners": "100,000–150,000 inhabitants",
    "150.000 tot 250.000 inwoners": "150,000–250,000 inhabitants",
    "250.000 inwoners of meer": "250,000 or more inhabitants",
    # Amsterdam districts / metro area
    "Stadsdeel Centrum": "District Centrum",
    "Stadsdeel Noord": "District Noord",
    "Stadsdeel West (incl. Westpoort)": "District West (incl. Westpoort)",
    "Stadsdeel Nieuw-West": "District Nieuw-West",
    "Stadsdeel Zuid": "District Zuid",
    "Stadsdeel Oost": "District Oost",
    "Stadsdeel Zuidoost": "District Zuidoost",
    "Basisregio Waterland": "Basic region Waterland",
    "Basisregio Zaanstreek": "Basic region Zaanstreek",
    "Basisregio IJmond": "Basic region IJmond",
    "Basisregio Zuid-Kennemerland": "Basic region Zuid-Kennemerland",
    "Basisregio Meerlanden": "Basic region Meerlanden",
    "Basisregio Amstelland": "Basic region Amstelland",
    "Basisregio Gooi en Vechtstreek": "Basic region Gooi en Vechtstreek",
    "Basisregio Almere + Zeewolde": "Basic region Almere + Zeewolde",
    "Basisregio Lelystad + Dronten": "Basic region Lelystad + Dronten",
    "Noord-Holland Noord": "Noord-Holland Noord",
    "Rest Nederland": "Rest of Netherlands",
    # Gender
    "Man": "Male",
    "Vrouw": "Female",
    # Age class
    "6 t/m 11 jaar": "6–11 years",
    "12 t/m 14 jaar": "12–14 years",
    "15 t/m 17 jaar": "15–17 years",
    "18 t/m 19 jaar": "18–19 years",
    "20 t/m 24 jaar": "20–24 years",
    "25 t/m 29 jaar": "25–29 years",
    "30 t/m 34 jaar": "30–34 years",
    "35 t/m 39 jaar": "35–39 years",
    "40 t/m 44 jaar": "40–44 years",
    "45 t/m 49 jaar": "45–49 years",
    "50 t/m 54 jaar": "50–54 years",
    "55 t/m 59 jaar": "55–59 years",
    "60 t/m 64 jaar": "60–64 years",
    "65 t/m 69 jaar": "65–69 years",
    "70 t/m 74 jaar": "70–74 years",
    "75 t/m 79 jaar": "75–79 years",
    "80 jaar of ouder": "80 years or older",
    "99 jaar of ouder": "99 years or older",
    # Migration background
    "Nederlandse achtergrond": "Dutch background",
    "Westerse migratieachtergrond": "Western migration background",
    "Niet-westerse migratieachtergrond": "Non-western migration background",
    # Paid work
    "Geen betaald werk": "No paid work",
    "Minder dan 12 uur per week": "Less than 12 hours per week",
    "12 tot 30 uur per week": "12–30 hours per week",
    "30 uur per week of meer": "30 or more hours per week",
    "Niet gevraagd; OP jonger dan 15 jaar": "Not asked; respondent under 15",
    # Unpaid activity
    "Geen onbetaalde bezigheid": "No unpaid activity",
    "Huisvrouw/huisman": "Homemaker",
    "Gepensioneerd/VUT": "Retired/early retirement",
    "Scholier/student": "Pupil/student",
    "Arbeidsongeschikt": "Work-disabled",
    "Werkloos": "Unemployed",
    "Onbetaald werkend": "Unpaid work",
    # Social participation
    "Werkzaam 12 tot 30 uur per week": "Employed 12–30 hours per week",
    "Werkzaam 30 uur of meer per week": "Employed 30 or more hours per week",
    "Eigen huishouding": "Own household",
    # Education
    "Geen opleiding voltooid": "No education completed",
    "Basisonderwijs, lager onderwijs": "Primary school",
    "Lager beroepsonderwijs of vmbo, vbo, lwoo, vso, vglo, mavo, ulo, mulo": "Lower vocational or pre-vocational secondary education",
    "Middelbaar beroepsonderwijs of havo, atheneum, gymnasium, mms, hbs": "Intermediate vocational or senior secondary education",
    "Hoger beroepsonderwijs, universiteit": "Higher vocational education or university",
    "Andere opleiding": "Other education",
    # Income deciles
    "Eerste 10% groep": "1st decile",
    "Tweede 10% groep": "2nd decile",
    "Derde 10% groep": "3rd decile",
    "Vierde 10% groep": "4th decile",
    "Vijfde 10% groep": "5th decile",
    "Zesde 10% groep": "6th decile",
    "Zevende 10% groep": "7th decile",
    "Achtste 10% groep": "8th decile",
    "Negende 10% groep": "9th decile",
    "Tiende 10% groep": "10th decile",
    "Inkomen onbekend": "Income unknown",
    "Welvaart onbekend": "Wealth unknown",
    # Low income threshold
    "Inkomen tot 80% lage-inkomensgrens": "Income below 80% of low-income threshold",
    "Inkomen van 80% tot 85% lage-inkomensgrens": "Income 80–85% of low-income threshold",
    "Inkomen van 85% tot 90% lage-inkomensgrens": "Income 85–90% of low-income threshold",
    "Inkomen van 90% tot 95% lage-inkomensgrens": "Income 90–95% of low-income threshold",
    "Inkomen van 95% tot 100% lage-inkomensgrens": "Income 95–100% of low-income threshold",
    "Inkomen van 100% tot 105% lage-inkomensgrens": "Income 100–105% of low-income threshold",
    "Inkomen van 105% tot 110% lage-inkomensgrens": "Income 105–110% of low-income threshold",
    "Inkomen van 110% lage-inkomensgrens of hoger": "Income 110%+ of low-income threshold",
    # Social minimum
    "Inkomen tot 101% sociaal minimum": "Income below 101% of social minimum",
    "Inkomen van 101% tot 105% sociaal minimum": "Income 101–105% of social minimum",
    "Inkomen van 105% tot 110% sociaal minimum": "Income 105–110% of social minimum",
    "Inkomen van 110% tot 115% sociaal minimum": "Income 110–115% of social minimum",
    "Inkomen van 115% tot 120% sociaal minimum": "Income 115–120% of social minimum",
    "Inkomen van 120% tot 130% sociaal minimum": "Income 120–130% of social minimum",
    "Inkomen van 130% tot 140% sociaal minimum": "Income 130–140% of social minimum",
    "Inkomen van 140% tot 150% sociaal minimum": "Income 140–150% of social minimum",
    "Inkomen van 150% sociaal minimum of hoger": "Income 150%+ of social minimum",
    # Licences – household counts
    "Geen autorijbewijzen": "No car licences",
    "9 autorijbewijzen of meer": "9 or more car licences",
    "Geen motorfietsrijbewijzen": "No motorcycle licences",
    "9 motorfietsrijbewijzen of meer": "9 or more motorcycle licences",
    "Geen bromfietsrijbewijzen": "No moped licences",
    "9 bromfietsrijbewijzen of meer": "9 or more moped licences",
    # Cars
    "9 personenauto's of meer": "9 or more cars",
    # Fuel types
    "Benzine": "Petrol",
    "Diesel": "Diesel",
    "LPG": "LPG",
    "Elektrisch": "Electric",
    "Volledig elektrisch": "Fully electric",
    "Plug-in hybride": "Plug-in hybrid",
    "Hybride met enkel opladen tijdens gebruik": "Hybrid (charge-during-use only)",
    "Geen elektrische auto": "No electric car",
    "Geen tweede brandstofsoort": "No secondary fuel type",
    "Anders met motor": "Other motorised",
    "Anders zonder motor": "Other non-motorised",
    # Car registration
    "Eigen naam": "Own name",
    "Ander lid huishouden": "Other household member",
    # Not applicable – cars
    "Niet van toepassing; Geen personenauto op naam huishouden": "Not applicable; no car registered to household",
    "Niet van toepassing: Geen personenauto op naam huishouden": "Not applicable; no car registered to household",
    "Niet van toepassing; Geen (tweede) personenauto op naam huishouden": "Not applicable; no (second) car registered to household",
    "Niet van toepassing: Geen (tweede) personenauto op naam huishouden": "Not applicable; no (second) car registered to household",
    "Niet van toepassing; Geen leaseauto of personenauto op naam bedrijf in huishouden": "Not applicable; no lease/company car in household",
    # Weight classes
    "Minder dan 951 kilogram": "Under 951 kg",
    "951 t/m 1150 kilogram": "951–1,150 kg",
    "1151 t/m 1350 kilogram": "1,151–1,350 kg",
    "1351 t/m 1550 kilogram": "1,351–1,550 kg",
    "Meer dan 1550 kilogram": "Over 1,550 kg",
    # Build year classes
    "2006 of eerder": "2006 or earlier",
    "2007 t/m 2009": "2007–2009",
    "2010 t/m 2012": "2010–2012",
    "2013 t/m 2015": "2013–2015",
    # Motorcycles / mopeds
    "9 motorfietsen of meer": "9 or more motorcycles",
    "9 bromfietsen of meer": "9 or more mopeds",
    "9 snorfietsen of meer": "9 or more scooters",
    "9 of meer": "9 or more",
    # Vehicle ownership classes
    "Geen van de genoemde vervoermiddelen": "None of the listed vehicles",
    "3 of meer auto's": "3 or more cars",
    "2 auto's": "2 cars",
    "1 auto": "1 car",
    "Minimaal 1 motor": "At least 1 motorcycle",
    "Minimaal 1 bromfiets": "At least 1 moped",
    "Minimaal 1 snorfiets": "At least 1 scooter",
    "Minimaal 1 elektrische fiets": "At least 1 electric bicycle",
    "Vervoermiddelenbezit huishouden onbekend": "Household vehicle ownership unknown",
    "Vervoermiddelenbezit OP onbekend": "Respondent vehicle ownership unknown",
    # Frequency of use
    "Dagelijks of vrijwel dagelijks": "Daily or almost daily",
    "Enkele keren per week": "A few times per week",
    "Enkele keren per maand": "A few times per month",
    "Enkele keren per jaar": "A few times per year",
    "Nooit of bijna nooit": "Never or almost never",
    "Niet van toepassing; OP jonger dan 17 jaar": "Not applicable; respondent under 17",
    # Student OV card
    "Studenten OV-chipkaart met weekabonnement": "Student transit card with weekday subscription",
    "Studenten OV-chipkaart met weekendabonnement": "Student transit card with weekend subscription",
    "Niet van toepassing; OP jonger dan 15 jaar of 40 jaar of ouder": "Not applicable; respondent under 15 or 40+",
    # Months
    "Januari": "January",
    "Februari": "February",
    "Maart": "March",
    "April": "April",
    "Mei": "May",
    "Juni": "June",
    "Juli": "July",
    "Augustus": "August",
    "September": "September",
    "Oktober": "October",
    "November": "November",
    "December": "December",
    # Weekdays
    "Zondag": "Sunday",
    "Maandag": "Monday",
    "Dinsdag": "Tuesday",
    "Woensdag": "Wednesday",
    "Donderdag": "Thursday",
    "Vrijdag": "Friday",
    "Zaterdag": "Saturday",
    # Traveled / not traveled
    "Serieverplaatsing(en)": "Series trip(s)",
    "Beroepsmatige vrachtwagenverplaatsing(en)": "Professional truck trip(s)",
    "Beroepsmatige serieverplaatsing(en) met vrachtwagen": "Professional truck series trip(s)",
    # Reason not traveled
    "Niet van toepassing; OP heeft verplaatsing(en)": "Not applicable; respondent made trip(s)",
    "Ziekte en/of blessure": "Illness and/or injury",
    "Lichamelijke beperkingen en/of handicap": "Physical limitations and/or disability",
    "Weersomstandigheden": "Weather conditions",
    "Thuiswerken of beroep aan huis": "Working from home or home-based occupation",
    "Studie thuis": "Studying at home",
    "Zorg voor gezinsleden": "Care for household members",
    "Geen activiteiten buitenshuis": "No activities outside the home",
    "Vervoer was te duur": "Transport was too expensive",
    "Geen geschikt vervoer beschikbaar": "No suitable transport available",
    "Verblijf in het buitenland": "Stay abroad",
    "Andere reden": "Other reason",
    # Illness duration
    "1 tot 6 dagen": "1–6 days",
    "7 dagen tot 4 weken": "7 days–4 weeks",
    "Langer dan 4 weken": "More than 4 weeks",
    "Niet van toepassing; Andere reden dan ziekte": "Not applicable; reason other than illness",
    # Weather type
    "Kou": "Cold",
    "Warmte": "Heat",
    "Regen/hagel/sneeuw": "Rain/hail/snow",
    "Wind/storm": "Wind/storm",
    "Gladheid": "Icy/slippery roads",
    "Mist": "Fog",
    "Wisselvallig weer": "Changeable weather",
    "Andere weersomstandigheden": "Other weather conditions",
    "Niet van toepassing; Andere reden dan het weer": "Not applicable; reason other than weather",
    # Reason abroad
    "Vrije tijd/vakantie": "Leisure/holiday",
    "Werk": "Work",
    "Studie": "Study",
    "Familiebezoek": "Family visit",
    "Niet van toepassing; Andere reden dan verblijf buitenland": "Not applicable; reason other than stay abroad",
    # Trip counts
    "OP heeft geen reguliere verplaatsing(en)": "Respondent made no regular trips",
    "OP heeft geen reguliere OV-verplaatsing(en)": "Respondent made no regular public transport trips",
    "OP heeft geen serieverplaatsing(en) zonder beroepsmatig met vrachtwagen": "Respondent made no series trips (excl. professional truck)",
    # E-bike type
    "Elektrische fiets": "Electric bicycle",
    "Speedpedelec": "Speed pedelec",
    "Niet gevraagd; OP heeft geen elektrische fiets gebruikt": "Not asked; respondent did not use electric bicycle",
    # Car usage types (not applicable)
    "Niet van toepassing; OP heeft geen verplaatsing(en)": "Not applicable; respondent made no trips",
    "Niet gevraagd": "Not asked",
    # Atypical day
    "Nee, geen specifieke bijzonderheden": "No, no specific special circumstances",
    "Nee, deze weekdag is altijd anders": "No, this weekday is always different",
    # Atypical reason
    "Vrije dag": "Day off",
    "Ziekte": "Illness",
    "Verkeer": "Traffic",
    "Afspraken": "Appointments",
    "Ziekte huishoudlid": "Illness of household member",
    "Samen reizen": "Travelling together",
    "Bagage": "Luggage",
    "Niet gevraagd; geen bijzonderheden aangegeven": "Not asked; no special circumstances reported",
    # Trip indicator
    "Geen nieuwe verplaatsing": "Not a new trip",
    "Nieuwe verplaatsing": "New trip",
    "Serieverplaatsing": "Series trip",
    "Beroepsmatige vrachtwagenverplaatsing": "Professional truck trip",
    "Beroepsmatige serieverplaatsing met vrachtwagen": "Professional truck series trip",
    # Trip purpose / motive
    "Naar huis": "Home",
    "Werken": "Work",
    "Zakelijk bezoek in werksfeer": "Business visit",
    "Beroepsmatig": "Professional",
    "Afhalen/brengen personen": "Picking up/dropping off persons",
    "Afhalen/brengen goederen": "Picking up/dropping off goods",
    "Onderwijs/cursus volgen": "Education/course",
    "Winkelen/boodschappen doen": "Shopping/groceries",
    "Visite/logeren": "Visiting/staying over",
    "Toeren/wandelen": "Touring/walking",
    "Sport/hobby": "Sport/hobby",
    "Overige vrijetijdsbesteding": "Other leisure",
    "Diensten/persoonlijke verzorging": "Services/personal care",
    "Ander doel": "Other purpose",
    "Van en naar het werk": "To and from work",
    "Zakelijk en beroepsmatig": "Business and professional",
    "Sociaal recreatief overig": "Other social-recreational",
    "Ander motief": "Other motive",
    # Shops
    "Niet van toepassing; Geen winkel bezocht": "Not applicable; no shop visited",
    # Work activity
    "Bouw": "Construction",
    "Service": "Service",
    "Bezorging": "Delivery",
    "Goederenvervoer": "Goods transport",
    "Personenvervoer": "Passenger transport",
    "Zorg": "Healthcare",
    "Hulpverlening": "Emergency/welfare services",
    "Zakelijk beroep": "Business profession",
    "Ophaaldienst": "Collection service",
    "Ander beroepsmatig werk": "Other professional work",
    "Niet van toepassing; geen beroepsmatige (serie)verplaatsing": "Not applicable; no professional (series) trip",
    # Departure location type
    "Eigen woonadres": "Own home address",
    "Ander thuisadres": "Other home address",
    "Een werkadres": "A work address",
    "Ander adres": "Other address",
    # Postal codes abroad
    "Geen vertrekpunt in België of Duitsland": "No departure point in Belgium or Germany",
    "Vertrekpunt in Nederland": "Departure point in Netherlands",
    "Vertrekpostcode in België onbekend": "Departure postal code in Belgium unknown",
    "Vertrekpostcode in Duitsland onbekend": "Departure postal code in Germany unknown",
    "Vertrekpostcode in Nederland onbekend": "Departure postal code in Netherlands unknown",
    "Postcode in België": "Postal code in Belgium",
    "Postcode in Duitsland": "Postal code in Germany",
    "Geen aankomstpunt in België of Duitsland": "No arrival point in Belgium or Germany",
    "Aankomstpunt in Nederland": "Arrival point in Netherlands",
    "Aankomstpostcode in België onbekend": "Arrival postal code in Belgium unknown",
    "Aankomstpostcode in Duitsland onbekend": "Arrival postal code in Germany unknown",
    "Aankomstpostcode in Nederland onbekend": "Arrival postal code in Netherlands unknown",
    "Geen vertrekpunt in Nederland": "No departure point in Netherlands",
    "Geen aankomstpunt in Nederland": "No arrival point in Netherlands",
    # Border crossing
    "Geen grensovergang": "No border crossing",
    "Grenspostcode in Nederland onbekend": "Border postal code in Netherlands unknown",
    "Grenspostcode in België": "Border postal code in Belgium",
    "Grenspostcode in Duitsland": "Border postal code in Germany",
    "Grenspostcode in buitenland onbekend": "Border postal code abroad unknown",
    # Distance classes
    "0,1 tot 0,5 km": "0.1–0.5 km",
    "0,5 tot 1,0 km": "0.5–1.0 km",
    "1,0 tot 2,5 km": "1.0–2.5 km",
    "2,5 tot 3,7 km": "2.5–3.7 km",
    "3,7 tot 5,0 km": "3.7–5.0 km",
    "5,0 tot 7,5 km": "5.0–7.5 km",
    "7,5 tot 10 km": "7.5–10 km",
    "10 tot 15 km": "10–15 km",
    "15 tot 20 km": "15–20 km",
    "20 tot 30 km": "20–30 km",
    "30 tot 40 km": "30–40 km",
    "40 tot 50 km": "40–50 km",
    "50 tot 75 km": "50–75 km",
    "75 tot 100 km": "75–100 km",
    "100 km of meer": "100 km or more",
    # Main mode
    "Personenauto": "Car",
    "Trein": "Train",
    "Bus": "Bus",
    "Tram": "Tram",
    "Metro": "Metro",
    "Niet-elektrische fiets": "Bicycle",
    "Te voet": "Walking",
    "Touringcar": "Coach",
    "Bestelauto": "Van",
    "Vrachtwagen": "Truck",
    "Camper": "Campervan",
    "Taxi/Taxibusje": "Taxi/minibus taxi",
    "Landbouwvoertuig": "Agricultural vehicle",
    "Motor": "Motorcycle",
    "Bromfiets": "Moped",
    "Snorfiets": "Scooter",
    "Gehandicaptenvervoermiddel met motor": "Motorised mobility aid",
    "Gehandicaptenvervoermiddel zonder motor": "Non-motorised mobility aid",
    "Skates/skeelers/step": "Skates/rollerblades/kick scooter",
    "Boot": "Boat",
    # Mode role
    "Bestuurder": "Driver",
    "Passagier": "Passenger",
    "Niet van toepassing; hoofdvervoermiddel is geen personen- of bestelauto": "Not applicable; main mode is not a car or van",
    "Niet van toepassing; ritvervoermiddel is geen personen- of bestelauto": "Not applicable; leg mode is not a car or van",
    # Mode class
    "Personenauto - bestuurder": "Car – driver",
    "Personenauto - passagier": "Car – passenger",
    "Bus/tram/metro": "Bus/tram/metro",
    "Fiets": "Bicycle",
    # Departure time classes
    "0 tot 4.00 uur": "00:00–04:00",
    "4.00 tot 7.00 uur": "04:00–07:00",
    "7.00 tot 8.00 uur": "07:00–08:00",
    "8.00 tot 9.00 uur": "08:00–09:00",
    "9.00 tot 12.00 uur": "09:00–12:00",
    "12.00 tot 13.00 uur": "12:00–13:00",
    "13.00 tot 14.00 uur": "13:00–14:00",
    "14.00 tot 16.00 uur": "14:00–16:00",
    "16.00 tot 17.00 uur": "16:00–17:00",
    "17.00 tot 18.00 uur": "17:00–18:00",
    "18.00 tot 19.00 uur": "18:00–19:00",
    "19.00 tot 20.00 uur": "19:00–20:00",
    "20.00 tot 24.00 uur": "20:00–24:00",
    # Travel time classes
    "1 tot 5 minuten": "1–5 minutes",
    "5 tot 10 minuten": "5–10 minutes",
    "10 tot 15 minuten": "10–15 minutes",
    "15 tot 20 minuten": "15–20 minutes",
    "20 tot 25 minuten": "20–25 minutes",
    "25 tot 30 minuten": "25–30 minutes",
    "30 tot 45 minuten": "30–45 minutes",
    "45 tot 60 minuten": "45–60 minutes",
    "60 tot 90 minuten": "60–90 minutes",
    "90 tot 120 minuten": "90–120 minutes",
    "120 minuten of meer": "120 minutes or more",
    "Geen reguliere verplaatsing in Nederland": "No regular trip in Netherlands",
    # Children along
    # Work trip sequence
    "Separate verplaatsing vanwege werk": "Single work trip",
    "1e van 2 opeenvolgende verplaatsingen vanwege werk": "1st of 2 consecutive work trips",
    "2e van 2 opeenvolgende verplaatsingen vanwege werk": "2nd of 2 consecutive work trips",
    "1e van 3 opeenvolgende verplaatsingen vanwege werk": "1st of 3 consecutive work trips",
    "2e van 3 opeenvolgende verplaatsingen vanwege werk": "2nd of 3 consecutive work trips",
    "3e van 3 opeenvolgende verplaatsingen vanwege werk": "3rd of 3 consecutive work trips",
    "1e van door serie opgevolgde verplaatsing vanwege werk": "1st of work trips followed by a series trip",
    "Serieverplaatsing vanwege werk": "Series work trip",
    "Niet van toepassing; geen verplaatsing vanwege werk": "Not applicable; no work trip",
    # Series trip addresses
    "6 t/m 10": "6–10",
    "11 t/m 20": "11–20",
    "21 of meer": "21 or more",
    # Amsterdam area check
    "Geen inwoner gemeente Amsterdam": "Not a resident of Amsterdam municipality",
    # Leg indicator
    "Nieuwe rit": "New leg",
    "Buitenlandse rit": "Foreign leg",
    "Rit van beroepsmatige vrachtwagenverplaatsing": "Leg of professional truck trip",
    # Leg distance
    "Geen rit in Nederland": "No leg in Netherlands",
    "Geen rit in het buitenland": "No leg abroad",
    # Car occupants
    "Niet van toepassing; OP heeft geen autorit": "Not applicable; respondent made no car leg",
    # Train group size
    "9 tot 12 personen": "9–12 persons",
    "12 tot 20 personen": "12–20 persons",
    "20 of meer personen": "20 or more persons",
    "Niet van toepassing; OP heeft geen treinrit": "Not applicable; respondent made no train leg",
    # Speed correction
    "Ritafstand verkleind": "Leg distance reduced",
    "Ritreisduur vergroot": "Leg travel time increased",
    "Ritafstand verkleind en ritreisduur vergroot": "Leg distance reduced and travel time increased",
    "Ritafstand vergroot": "Leg distance increased",
    "Ritreisduur verkleind": "Leg travel time reduced",
    "Ritafstand vergroot en ritreisduur verkleind": "Leg distance increased and travel time reduced",
    # Flight removed
    "Ja, hiervoor": "Yes, before",
    "Ja, hierna": "Yes, after",
    "Ja, hiervoor en hierna": "Yes, before and after",
    # Series mode not applicable
    "Niet van toepassing; geen tweede vervoermiddel": "Not applicable; no second mode",
    "Niet van toepassing; geen derde vervoermiddel": "Not applicable; no third mode",
    "Niet van toepassing; geen vierde vervoermiddel": "Not applicable; no fourth mode",
    # Train stations
    "Niet van toepassing; Ritvervoermiddel is geen trein": "Not applicable; leg mode is not a train",
    # Provinces (kept in Dutch where no standard English name differs)
    "Fryslân": "Friesland",
    "Noord-Holland": "North Holland",
    "Zuid-Holland": "South Holland",
    "Noord-Brabant": "North Brabant",
    "Groningen": "Groningen",
    "Drenthe": "Drenthe",
    "Overijssel": "Overijssel",
    "Flevoland": "Flevoland",
    "Gelderland": "Gelderland",
    "Utrecht": "Utrecht",
    "Zeeland": "Zeeland",
    "Limburg": "Limburg",
    # Other missing code labels
    "Geen afstand in het buitenland": "No distance abroad",
}
