column_mappings:
    default:
        "PERSONID": "pid" # id within household
        "HOUSEID": "hid"
        "R_AGE": "age"
        "EDUC": "education"
        "MEDCOND": "disability"  # actually difficulty travelling
        "WORKER": "employed"
        "PRMACT": "employment"
        "R_RELAT": "relationship"
        "R_SEX": "sex"
        "DRIVER": "has_licence"  # actually derived
        # "HBHUR": "rurality"
        

"education":
    "default": {
        -9: "unknown",
        -8: "unknown",
        -7: "unknown",
        -1: "n/a",
        1: "school",
        2: "high-school",
        3: "high-school",
        4: "degree",
        5: "degree",
    }
    2022: {
        -1: "n/a",
        1: "school",
        2: "school",
        3: "high-school",
        4: "high-school",
        5: "high-school",
        6: "degree",
        7: "degree",
        8: "degree",
    }
    2001: {
        -8: "unknown",
        -7: "unknown",
        -1: "n/a",
        -9: "unknown",
        1: "school",
        2: "school",
        3: "high-school",
        4: "high-school",
        5: "high-school",
        6: "degree",
        7: "degree",
        8: "degree",
    }
"disability":
    "default": {
        -1: "unknown",
        -7: "unknown",
        -8: "unknown",
        -9: "unknown",
        1: "yes",
        2: "no",
    }
"employment":
    2022: {
        -9: "unknown",
        -8: "unknown",
        -7: "unknown",
        -1: "n/a",
        1: "unemployed",
        2: "unemployed",
        3: "unemployed",
        4: "student",
        5: "retired",
        97: "other",
    }
    "default": {
        -9: "unknown",
        -8: "unknown",
        -7: "unknown",
        -1: "n/a",
        1: "employed",
        2: "unemployed",  # temporarily unemployed
        3: "unemployed",
        4: "unemployed",  # home maker
        5: "student",
        6: "retired",
        7: "other",
        97: "other",
    }
"race":
    "default": {
        -9: "unknown",
        -8: "unknown",
        -7: "unknown",
        1: "white",
        2: "black",
        3: "asian",
        4: "american_native",
        5: "american_native",
        6: "other",
        97: "other",
    }
"relationship":
    "default": {
        -9: "unknown",
        -8: "unknown",
        -7: "unknown",
        1: "self",
        2: "partner",
        3: "child",
        4: "parent",
        5: "sibling",
        6: "other",
        7: "partner",
        8: "other",
    }
    2017: {
        -9: "unknown",
        -8: "unknown",
        -7: "unknown",
        1: "self",
        2: "partner",
        3: "child",
        4: "parent",
        5: "sibling",
        6: "other",
        7: "other",
    }
    2022: {
        -9: "unknown",
        1: "partner",
        2: "child",
        3: "parent",
        4: "sibling",
        5: "other",
        6: "other",
        7: "self",
    }
"sex":
    "default": {
        -7: "unknown",
        -8: "unknown",
        -9: "unknown",
        1: "male",
        2: "female",
    }
"has_licence":
    "default": {
        -9: "unknown",
        -8: "unknown",
        -7: "unknown",
        -1: "unknown",
        1: "yes",
        2: "no",
    }
rurality:
    default:
        -9: unknown
        1: rural
        2: suburban
        3: urban
        4: suburban
        5: urban
