attributes:
  hid:
    dtype: string
    default: False
  pid:
    dtype: string
    default: False
  age:
    dtype: int
    default: True
    min: 0
    max: 120
  hh_size:
    dtype: int
    default: True
    min: 1
    max: 100
  hh_income:
    dtype: numeric
    default: True
    min: 0
  sex:
    dtype: str
    default: True
    set: [male, female, other, unknown]
  dwelling:
    dtype: str
    default: True
    set: [house, flat, other, unknown]
  ownership:
    dtype: str
    default: True
    set: [owned, rented, other, unknown]
  vehicles:
    dtype: int
    default: True
    min: 0
    max: 100
  disability:
    dtype: str
    default: True
    set: ["yes", "no", unknown]
  education:
    dtype: str
    default: True
    set: [n/a, some, none, school, high-school, degree, unknown]
  can_wfh:
    dtype: str
    default: True
    set: ["yes", "no", unknown, n/a]
  occupation:
    dtype: str
    default: True
    set: [n/a, clerical, manual, managerial, operator, professional, service, other, technical, unknown]
  race:
    dtype: str
    default: True
    set: [white, black, asian, non-white, other, multiracial, unknown]
  has_licence:
    dtype: str
    default: True
    set: [n/a, "yes", "no", unknown]
  relationship:
    dtype: str
    default: True
    set: [self, partner, child, parent, sibling, unrelated, relative, other, unknown]
  employment:
    dtype: str
    default: True
    set: [n/a, employed, ft-employed, pt-employed, unemployed, retired, student, other, unknown]
  country:
    dtype: str
    default: True
  source:
    dtype: str
    default: True
  year:
    dtype: int
    default: True
  month:
    dtype: int
    default: True
    min: 1
    max: 12
  day:
    dtype: str
    default: True
    set: [monday, tuesday, wednesday, thursday, friday, saturday, sunday, unknown]
  rurality:
    dtype: str
    default: True
    set: [urban, suburban, rural, unknown]
  weight:
    dtype: float
    default: True
    min: 0

trips:
  pid:
    dtype: string
    default: None
  seq:
    dtype: int
    default: None
    min: 0
  ozone:
    dtype: str
    default: True
    set: [urban, suburban, rural, unknown]
  dzone:
    dtype: str
    default: True
    set: [urban, suburban, rural, unknown]
  oact:
    dtype: str
    default: True
    set: [home, work, education, shop, leisure, medical, visit, escort, other, unknown]
  dact:
    dtype: str
    default: True
    set: [home, work, education, shop, leisure, medical, visit, escort, other, unknown]
  mode:
    dtype: str
    default: True
    set: [walk, bike, car, bus, rail, other, unknown]
  tst:
    dtype: int
    default: None
    min: 0
  tet:
    dtype: int
    default: None
    min: 0
  distance:
    dtype: float
    default: None
    min: 0
